/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.sahaj;

import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.stream.IntStream;

public class App {

  public static void main(String[] args) {
    final ThreadFactory factory = Thread.ofVirtual().name("routine-", 0).factory();
    try (var executor = Executors.newThreadPerTaskExecutor(factory)) {
      IntStream.range(0, Runtime.getRuntime().availableProcessors() + 10)
        .forEach(i -> executor.submit(() -> {
          System.out.println(Thread.currentThread() + " - Hello, I'm task number " + i);
          try {
            Thread.sleep(10000L);
          } catch (InterruptedException e) {
            throw new RuntimeException(e);
          }
        }));
    }
  }
}
